# Generated by Django 4.2 on 2025-02-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeCuenta', models.IntegerField(unique=True)),
                ('numeroComprobante', models.CharField(max_length=20)),
                ('tipoDeComprobante', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=1000)),
                ('debito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
